// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// });

// Mock supabase client to prevent build errors
export const supabase = {
  from: () => ({
    select: () => ({ eq: () => ({ maybeSingle: () => ({}), order: () => ({}) }) }),
    // Add other mocked methods if strictly necessary for build, 
    // but we are replacing usage in hooks anyway.
  })
} as any;